### ISSUE TITLE
How to run Douyin_Downloader

### ISSUE THREAD

**Issue by andrewgf988** [palm578/douyin_downloader#1]
Heloo friend, when i open douyin_download,py nothing happened. I've setuped Python 3.10. Maybe i missed something ?

**Comment by palm578** [comment]
Firstly, the depending python modules should be install, such as selenium and so on.
Secondly, the program depends on chrome browser. You should install a chrome browser, and download the corresponding chromedriver to the working directory.
If it does not work after you complete the mentioned requirements, you may paste the output of program here.
